// <auto-generated />
using System;
using Agrotechteste.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Agrotechteste.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Agrotechteste.Models.Administrador", b =>
                {
                    b.Property<int>("idADM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idADM"));

                    b.Property<string>("nomeADM")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("senhaADM")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("idADM");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("Agrotechteste.Models.Cliente", b =>
                {
                    b.Property<int>("idCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idCliente"));

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Id_cliente")
                        .HasColumnType("int");

                    b.Property<string>("bairro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("cidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("complementar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("cpf_cnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("data_nascimento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("genero_cliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nomeCliente")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("numero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("rg_cliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("rua")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("tipo_cliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("idCliente");

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("Agrotechteste.Models.Usuario", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idUsuario"));

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nome_usuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("senha_usuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("idUsuario");

                    b.ToTable("usuario", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
